export default [
  {
    id: 1,
    sn: "01",
    vehicleImage: "https://example.com/images/vehicle1.png",
    vehicleID: "FMS-EN-00123",
    vehicleType: "SUV",
    plateNumber: "EN1234NG",
    lastServiceDate: "30th January 2023",
    nextServiceDate: "30th January 2023",
    status: "ok",
  },
  {
    id: 2,
    sn: "01",
    vehicleImage: "https://example.com/images/vehicle1.png",
    vehicleID: "FMS-EN-00123",
    vehicleType: "SUV",
    plateNumber: "EN1234NG",
    lastServiceDate: "30th January 2023",
    nextServiceDate: "30th January 2023",
    status: "issue",
  },
  {
    id: 3,
    sn: "01",
    vehicleImage: "https://example.com/images/vehicle1.png",
    vehicleID: "FMS-EN-00123",
    vehicleType: "SUV",
    plateNumber: "EN1234NG",
    lastServiceDate: "30th January 2023",
    nextServiceDate: "30th January 2023",
    status: "ok",
  },
  {
    id: 4,
    sn: "01",
    vehicleImage: "https://example.com/images/vehicle1.png",
    vehicleID: "FMS-EN-00123",
    vehicleType: "SUV",
    plateNumber: "EN1234NG",
    lastServiceDate: "30th January 2023",
    nextServiceDate: "30th January 2023",
    status: "ok",
  },
  {
    id: 5,
    sn: "01",
    vehicleImage: "https://example.com/images/vehicle1.png",
    vehicleID: "FMS-EN-00123",
    vehicleType: "SUV",
    plateNumber: "EN1234NG",
    lastServiceDate: "30th January 2023",
    nextServiceDate: "30th January 2023",
    status: "issue",
  },
];
