export default [
  {
    id: 1,
    sn: "01",
    orderNumber: "ORD-20231001",
    procurementType: "Purchase",
    vendor: "ABC Supplies Co.",
    itemDescription: "Office Chairs",
    quantity: 50,
    totalCost: "$2,500",
    deliveryStatus: "Delivered",
  },
  {
    id: 2,
    sn: "02",
    orderNumber: "ORD-20231002",
    procurementType: "Lease",
    vendor: "XYZ Tech Rentals",
    itemDescription: "Laptops - Dell XPS 13",
    quantity: 10,
    totalCost: "$10,000",
    deliveryStatus: "Pending",
  },
  {
    id: 3,
    sn: "03",
    orderNumber: "ORD-20231003",
    procurementType: "Purchase",
    vendor: "Global Electronics",
    itemDescription: "Projectors - Epson HD",
    quantity: 5,
    totalCost: "$3,750",
    deliveryStatus: "Shipped",
  },
  {
    id: 4,
    sn: "04",
    orderNumber: "ORD-20231004",
    procurementType: "Rental",
    vendor: "Furniture Rentals Ltd.",
    itemDescription: "Conference Tables",
    quantity: 4,
    totalCost: "$800",
    deliveryStatus: "Delivered",
  },
  {
    id: 5,
    sn: "05",
    orderNumber: "ORD-20231005",
    procurementType: "Purchase",
    vendor: "Stationery World",
    itemDescription: "Printer Paper - A4",
    quantity: 1000,
    totalCost: "$300",
    deliveryStatus: "Processing",
  },
  {
    id: 6,
    sn: "06",
    orderNumber: "ORD-20231006",
    procurementType: "Lease",
    vendor: "Tech Solutions",
    itemDescription: "Desktop Monitors - 24 inch",
    quantity: 20,
    totalCost: "$4,000",
    deliveryStatus: "Backordered",
  },
];
