export default [
  {
    id: 1,
    sn: "01",
    recipientName: "Chidubem Anowor",
    vehicleID: "423 ENSG",
    vehicleType: "SUV",
    vehicleColor: "Ash Color",
    makeModel: "Toyota Land Cruiser 2022",
    engineNumber: "1KD-FTV-88746",
    action: "View Details",
  },
  {
    id: 2,
    sn: "01",
    recipientName: "Chidubem Anowor",
    vehicleID: "423 ENSG",
    vehicleType: "SUV",
    vehicleColor: "Ash Color",
    makeModel: "Toyota Land Cruiser 2022",
    engineNumber: "1KD-FTV-88746",
    action: "View Details",
  },
  {
    id: 3,
    sn: "01",
    recipientName: "Chidubem Anowor",
    vehicleID: "423 ENSG",
    vehicleType: "SUV",
    vehicleColor: "Ash Color",
    makeModel: "Toyota Land Cruiser 2022",
    engineNumber: "1KD-FTV-88746",
    action: "View Details",
  },
  {
    id: 4,
    sn: "01",
    recipientName: "Chidubem Anowor",
    vehicleID: "423 ENSG",
    vehicleType: "SUV",
    vehicleColor: "Ash Color",
    makeModel: "Toyota Land Cruiser 2022",
    engineNumber: "1KD-FTV-88746",
    action: "View Details",
  },
  {
    id: 5,
    sn: "01",
    recipientName: "Chidubem Anowor",
    vehicleID: "423 ENSG",
    vehicleType: "SUV",
    vehicleColor: "Ash Color",
    makeModel: "Toyota Land Cruiser 2022",
    engineNumber: "1KD-FTV-88746",
    action: "View Details",
  },
  {
    id: 6,
    sn: "01",
    recipientName: "Chidubem Anowor",
    vehicleID: "423 ENSG",
    vehicleType: "SUV",
    vehicleColor: "Ash Color",
    makeModel: "Toyota Land Cruiser 2022",
    engineNumber: "1KD-FTV-88746",
    action: "View Details",
  },
];
