export default [
  {
    id: 1,
    sn: "01",
    vehicleImage: "https://example.com/images/vehicle1.png", // Placeholder URL for the vehicle image
    vehicleID: "FMS-EN-00123",
    vehicleType: "SUV",
    makeModel: "Toyota Land Cruiser 2022",
    engineNumber: "1KD-FTV-88746",
    action: "View Details",
  },
  {
    id: 2,
    sn: "01",
    vehicleImage: "https://example.com/images/vehicle1.png",
    vehicleID: "FMS-EN-00123",
    vehicleType: "SUV",
    makeModel: "Toyota Land Cruiser 2022",
    engineNumber: "1KD-FTV-88746",
    action: "View Details",
  },
  {
    id: 3,
    sn: "01",
    vehicleImage: "https://example.com/images/vehicle1.png",
    vehicleID: "FMS-EN-00123",
    vehicleType: "SUV",
    makeModel: "Toyota Land Cruiser 2022",
    engineNumber: "1KD-FTV-88746",
    action: "View Details",
  },
  {
    id: 4,
    sn: "01",
    vehicleImage: "https://example.com/images/vehicle1.png",
    vehicleID: "FMS-EN-00123",
    vehicleType: "SUV",
    makeModel: "Toyota Land Cruiser 2022",
    engineNumber: "1KD-FTV-88746",
    action: "View Details",
  },
  {
    id: 5,
    sn: "01",
    vehicleImage: "https://example.com/images/vehicle1.png",
    vehicleID: "FMS-EN-00123",
    vehicleType: "SUV",
    makeModel: "Toyota Land Cruiser 2022",
    engineNumber: "1KD-FTV-88746",
    action: "View Details",
  },
  {
    id: 6,
    sn: "01",
    vehicleImage: "https://example.com/images/vehicle1.png",
    vehicleID: "FMS-EN-00123",
    vehicleType: "SUV",
    makeModel: "Toyota Land Cruiser 2022",
    engineNumber: "1KD-FTV-88746",
    action: "View Details",
  },
];
